# Generated by Django 4.2.4 on 2023-08-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kontakt_email', models.EmailField(max_length=254)),
                ('telefonnummer', models.CharField(blank=True, max_length=15, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('bemerkungen', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mitarbeiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefonnummer', models.CharField(blank=True, max_length=15, null=True)),
                ('geburtsdatum', models.DateField(blank=True, null=True)),
                ('eintrittsdatum', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField()),
                ('preis', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lagerbestand', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('startdatum', models.DateField()),
                ('enddatum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=50)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('faelligkeitsdatum', models.DateField()),
                ('bezahlt_am', models.DateField(blank=True, null=True)),
                ('bemerkungen', models.TextField(blank=True, null=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.kunde')),
                ('projekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_app.projekt')),
            ],
        ),
        migrations.CreateModel(
            name='Aufgabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschreibung', models.TextField()),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=50)),
                ('projekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_app.projekt')),
                ('zugeordnet_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='erp_app.mitarbeiter')),
            ],
        ),
    ]
